f = figure(1);
clf

genOptions = uipanel(...
	'Parent',f,...
	'Units','normalized',...
	'Position',[0.3 0.4, 0.2 0.4]);
n = 15;
theNums = 1:n;
numBoxes = gobjects(n,1);
visCount = n;
for i = 1:n
	numBoxes(i) = uicontrol(...
		'Parent',genOptions,...
		'Units','normalized',...
		'Style','edit',...
		'String',num2str(theNums(i)),...
		'UserData',theNums(i),...
		'Position',[0 1-0.125*i 0.75 0.125],...
		'FontSize',12);
	if numBoxes(i).Position(2) < 0
		numBoxes(i).Visible = 'off';
		visCount = visCount - 1;
	end
end
tableSlider = uicontrol(...
	'Parent',genOptions,...
	'Units','normalized',...
	'Style','slider',...
	'Position',[0.02+sum(numBoxes(1).Position([1 3])) 0 0.98-numBoxes(1).Position(3) 1],...
	'Min',visCount/n,...
	'Max',1,...
	'Value',1,...
	'SliderStep',[0.025 .05],...
	'FontSize',12,...
	'Callback',{@tableScroll, numBoxes});



function [] = tableScroll(src, evt, numBoxes)
	scroll = 1 - src.Value;
	for i = 1:length(numBoxes)
		numBoxes(i).Position(2) = 1 + numBoxes(1).Position(4)*(scroll*length(numBoxes) - i);
		if numBoxes(i).Position(2) > 1 || numBoxes(i).Position(2) < -numBoxes(1).Position(4)
			numBoxes(i).Visible = 'off';
		else
			numBoxes(i).Visible = 'on';
		end
	end
end












